apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: girus-1
  name: girus-1
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args: 
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
